set -ex

cmake -S "${SRC_DIR}/${ROBOPLAN_PACKAGE}" \
  -B "build/${ROBOPLAN_PACKAGE}" \
  -G Ninja \
  ${CMAKE_ARGS} \
  -DBUILD_PYTHON_BINDINGS=OFF \
  -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
cmake --build "build/${ROBOPLAN_PACKAGE}"
cmake --install "build/${ROBOPLAN_PACKAGE}"
